services:
  app:
    build:
      context: .
    image: "llms4eu:latest"
    restart: unless-stopped
    env_file: .env
    develop:
      watch:
        - action: sync
          path: ./llms4eu
          target: /app/llms4eu
        - action: rebuild
          path: uv.lock
